name: Build Wheels

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:

jobs:
  build:
    name: Build Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      QT_VERSION: "6.5.3"
      QT_INSTALL_DIR: Qt
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]

    steps:
      - name: Set environment variables for host OS
        shell: bash
        run: |
          case "${{ runner.os }}" in
            Linux)
              echo "QT_HOST_OS=linux" >> $GITHUB_ENV
              echo "QT_ARCH=gcc_64" >> $GITHUB_ENV
              ;;
            macOS)
              echo "QT_HOST_OS=mac" >> $GITHUB_ENV
              echo "QT_ARCH=clang_64" >> $GITHUB_ENV
              ;;
            Windows)
              echo "QT_HOST_OS=windows" >> $GITHUB_ENV
              echo "QT_ARCH=win64_msvc2019_64" >> $GITHUB_ENV
              ;;
          esac

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Install Qt
        run: uvx --from aqtinstall aqt install-qt "$QT_HOST_OS" desktop "$QT_VERSION" "$QT_ARCH" --outputdir "$QT_INSTALL_DIR"

      - name: Build wheels via cibuildwheel
        uses: pypa/cibuildwheel@v2.22

      - name: Upload wheels artifactss
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ runner.os }}-${{ runner.arch }}
          path: ./wheelhouse/*.whl
